### PR TITLE
show a modal warning if no reward scores would be earned

### PR DESCRIPTION
**Pull request by v-morlock**
the backend doesn't return the correct data right now, for testing add `true || `

image

Please provide a short description of the change or if the change is sufficiently described in the GitHub issue, provide a link to the issue.

## How has this been tested?

Please describe the test strategy you followed.

- [ ] automated unit test
- [ ] automated integration test
- [ ] automated acceptance test
- [ ] manual, exploratory test

In case of manual test, please document the test well including a set of user instructions and prerequisites. Each including an action, it's result, and where appropriate a screenshot.

## Checklist before requesting a review

- [ ] My code follows the [coding guidelines](https://github.com/IT-REX-Platform/wiki/blob/main/dev-manuals/backend/coding-guidelines.md) of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My code fulfilles all acceptance criteria
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have made corresponding changes to the documentation
- [ ] I have added explanation of architectural decision and rationales to [wiki/adr](https://github.com/IT-REX-Platform/wiki/tree/main/adr)
- [ ] I have updated the changes in the ticket description

## Checklist for reviewer

- [ ] The code works and does not throw errors
- [ ] The code is easy to understand and there are no confusing parts
- [ ] The code follows the [coding guidelines](https://github.com/IT-REX-Platform/wiki/blob/main/dev-manuals/backend/coding-guidelines.md) of this project
- [ ] The code change accomplishes what it is supposed to do
- [ ] I cannot think of any use case in which the code does not behave as intended
- [ ] The added and existing tests reasonably cover the code change
- [ ] I cannot think of any test cases, input or edge cases that should be tested in addition
- [ ] Description of the change is included in the documentation

### CODE REVIEW

**Comment by v-morlock** [comment]
Hast recht ich hab den check ergänzt, das hat gefehlt. Gerne mergen wenns dann so passt :)

**Comment by SkyDiverStar** [comment]
Ich sehe jetzt gerade auch erst, bräuchten wird das nicht auf für das Quiz?

**Comment by SkyDiverStar** [comment]
Außerdem, wir sind uns sicher, dass der NaN Fehler im Bild vom Anfang ein Backup Problem ist oder? Wissen die davon? Und falls wir nicht wissen, wie lange es bei denen braucht, bis es gefixt ist, sollten wir nicht einen anderen Text anzeigen, wie: "You just learned a few days ago. You will not earn any reward point by doing this now."

**Comment by v-morlock** [comment]
ist doch auch fürs quiz oder nicht?

**Comment by v-morlock** [comment]
und ich würd da jetzt kein workaround machen für den backend bug

**Comment by SkyDiverStar** [comment]
Ich sehe was du meinst mit dem Quiz, hab es vermutlich überflogen. Es scheint mir das mit dem Flashcard API changes hat die Funktion gekillt. Probiere es gerade aus, nachdem ich main in diesen branch lokal gemerged habe. 
Es reagiert nicht :(

**Pull request merged**
